### ISSUE TITLE
Intended status: informational

### ISSUE THREAD

**Issue by arndt-s** [oauth-wg/oauth-transaction-tokens#169]
Just happened to notice that the current category is Informational. Not an expert but it feels much more like a standard track document to me.

```yaml
stand_alone: true
ipr: trust200902
cat: info # Check
submissiontype: IETF
area: sec
wg: oauth
```
